#!/bin/bash
# testit -- test newly installed pipeline
# 20170907 Paul Huygen
export scriptname=$0
export thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
export socket="$(dirname $thisdir)"
export rundir=${socket}/run
source $rundir/conf
unset NAFLANG

while getopts ":l:" opt; do
  case $opt in
    l) NAFLANG=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

function testrun () {
    testlang=$1
    testdir=${thisdir}/test${testlang}
    mkdir -p ${testdir}
    rm -rf ${testdir}/*.naf
#    cp ${thisdir}/test.${testlang}.in.naf ${testdir}/in.naf
    ${rundir}/nlpp -k -t ${testdir} < ${thisdir}/test.${testlang}.in.naf >/dev/null
}

if
    [ -z ${NAFLANG+x} ]
then
    $scriptname -l "en"
    $scriptname -l "nl"
else
    if
	[ "$NAFLANG" == 'en' -o "$NAFLANG" == 'nl' ]
    then
	testrun "$NAFLANG"
    else
	echo "Invalid language: $NAFLANG."
	exit 1
    fi
fi
