#!/bin/bash
# 1. Install Ubuntu packages.
# 2. Make Python 3 the default.
# 3. Install Python packages.
# 20180507 Paul Huygen
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $thisdir/source
apt-get -y update
apt-get -y upgrade
apt-get -y install apt-utils wget
xargs -a <(awk '! /^ *(#|$)/' "$packagelist") -r -- apt-get -y install
ln -s /usr/bin/python3.5 /usr/local/bin/python
ln -s /usr/bin/pip3 /usr/local/bin/pip
pip install --upgrade pip
pip install lxml
pip install pyyaml
pip install --upgrade git+https://github.com/ixa-ehu/pynaf.git
pip install --upgrade requests
pip install networkx==1.11
pip install --upgrade kafnafparserpy

