#!/bin/bash
# testit -- test newly installed pipeline
# 20170907 Paul Huygen
export thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
bindir=${thisdir}
export confdir=/usr/local/etc/nlpp
keep_temp=1
if
    [ "$1" == 'k' ]
then
    keep_temp=0
fi
initscript=${confdir}/conf
source $initscript
scratchdir=`mktemp -d -t nlpp.XXXXXX`
res=0

function runmodule {
   local infile=$1
   local modnam=$2
   local outfile=$3
   cat ${infile} | $MODROOT/${modnam}/run > ${outfile}
   res=$?
}


# run_pipeline -- run the pipeline
# Assume current dir is work-dir, contains in.naf.
function run_pipeline () {
    naflang=$1
    modulelist=${confdir}/modules.${naflang}
    lastfile=in.naf
    while
	IFS=' ' read -r module || [[ -n "$module" ]]
    do
	echo "Annotate ${lastfile} with ${module}" >&2
        nextfile=${module}.naf
        cat ${lastfile} | ${MODROOT}/${module}/run >${module}.naf
	res=$?
	if
	    [ ${res} -gt 0 ]
	then
	    break
	fi
	lastfile=${module}.naf
    done < ${modulelist}
    ln -s ${lastfile} out.naf
}



cd $scratchdir
cat >in.naf
export naflang=`cat in.naf | $bindir/langdetect.py`
if
    [ "$naflang" != "nl" -a "$naflang" != "en" ]
then
    echo "Language $naflang is not supported." >&2
    exit 4
fi
run_pipeline $naflang
if
    [ $res -gt 0 ]
then
    echo "Pipeline has not been completed due to an error." >&2
    exit 4
fi
cat out.naf
if
    [ $keep_temp == 0 ]
then
    echo "$scratchdir kept" >&2
else
    rm -rf $scratchdir
fi


